### ISSUE TITLE
Remove the `hasmethod` check 

### ISSUE THREAD

**Issue by KristofferC** [SciML/DiffEqBase.jl#1095]
The `hasmethod` check in https://github.com/SciML/DiffEqBase.jl/blob/01fd8532d8f0aac2c30995c2a74a29ef0a173edf/src/callbacks.jl#L622 has been reported to have quite severe runtime penalty, at least on 1.10.2.

As far as I understand, this is some kind of compatibility check so moving that to top-level would be preferable.

**Comment by oscardssmith** [comment]
I though as of https://github.com/JuliaLang/julia/pull/48639, it should be done at compile time.

**Comment by KristofferC** [comment]
Yes, but it has been reported not to happen apparently.

**Comment by oscardssmith** [comment]
@vtjnash any idea why this would happen?

**Comment by vtjnash** [comment]
kwarg matching is a runtime feature, so it doesn't have a compile time component

**Comment by KristofferC** [comment]
Could the kwargs just be removed from this `hasmethod` check?

**Comment by KristofferC** [comment]
@oscardssmith, in which SciMLBase version was this new way of calling `reeval_internals_due_to_modification!` introduced? We can just do a top-level check for that version instead.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/SciMLBase.jl/releases/tag/v2.53.0 is the scimlbase part, but it's actually a downstream requirement on https://github.com/SciML/OrdinaryDiffEq.jl/pull/2467 existing (and figuring out what OrdinaryDiffEqCore version that's a part of is a doozy due to the issues with the tooling 😅)

**Comment by oscardssmith** [comment]
can't we at this point just delete the hasmethod check since it only exists for compatibility with old versions of OrdinaryDiffEq?

**Comment by KristofferC** [comment]
I deleted all `apply_discrete_callback!` from DiffEqBase and tests still pass... Wat.

**Comment by KristofferC** [comment]
> but it's actually a downstream requirement on https://github.com/SciML/OrdinaryDiffEq.jl/pull/2467

Wow, that is very weird how another package extends a method with a new keyword like that.

**Comment by ChrisRackauckas** [comment]
Agreed, we really need https://github.com/JuliaLang/julia/issues/55516. OrdinaryDiffEq and DiffEqBase are split mostly to lesson the load times of Sundials.jl and not for any real code separation reason.

**Comment by KristofferC** [comment]
It is still kind of weird how one function takes different kwargs depending on the integrator...

**Comment by ChrisRackauckas** [comment]
All of the integrators have been updated so this interface now just has kwargs for all current releases.

**Comment by KristofferC** [comment]
I was looking at https://github.com/SciML/SciMLBase.jl/blob/17f45482531981c25274dd9f0a7d8b934bc0a50b/src/integrator_interface.jl#L323-L335 which does not have a kwarg, or?

**Comment by ChrisRackauckas** [comment]
It's missing the kwarg. We need to update the interface spec, but since you can't really test interfaces well downstream that's a bug that just hadn't been caught yet. We need some language tooling to help here 😅.
