### ISSUE TITLE
Callback issue with condition is zero at tprev

### ISSUE THREAD

**Issue by tomaklutfu** [SciML/DiffEqBase.jl#266]
In below code snippet, the comment is counter intuitive because when derivative positive at a zero it is an upcrossing and vice versa. But, in general, we cannot make it up because there is also higher order roots. For my case, `previous_condition` is actually 0 and slight future condition is somewhat negative and next condition is positive. What next is it is treated as event occured and `find_zero` errors out with non-bracketing interval because actual start of the interval is at slight future and `tprev` is not at slight future in `zero_func`
https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/bd02c314adf08d0bb5223ad6e2d33383bb05e902/src/callbacks.jl#L346-L371
https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/bd02c314adf08d0bb5223ad6e2d33383bb05e902/src/callbacks.jl#L417-L420

Also, for avoiding similar error, exact zero at the end of interval checked but not at the beginning.
https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/bd02c314adf08d0bb5223ad6e2d33383bb05e902/src/callbacks.jl#L421-L423

**Comment by tomaklutfu** [comment]
More on the heuristic but not necessarily related to this issue directly.

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/bd02c314adf08d0bb5223ad6e2d33383bb05e902/src/callbacks.jl#L382-L397

In above branch, `elseif` part does not change `prev_sign` although changing `prev_sign_index`. Potentially, it can miss an event if it is at the end of the corresponding interval. Then, in the next iteration,  there can be spurficial event in the wrong interval when new_sign becomes opposite of prev_sign. Also, new_sign is not a sign but it doesn't matter I think.

**Comment by kanav99** [comment]
Higher order roots are something that we cannot do anything about I think. For making the results better, we have to increase `interp_points`.
> In above branch, elseif part does not change prev_sign although changing prev_sign_index
I dont think that would make a difference because as the sign flips, we break out of loop. So during the whole loop, `prev_sign` is invariant, so no need of re updating.

> Also, new_sign is not a sign but it doesn't matter I think.
Yeah it's just a float but works like a sign haha.

> For my case, previous_condition is actually 0 and slight future condition is somewhat negative and next condition is positive. What next is it is treated as event occured and find_zero errors out with non-bracketing interval because actual start of the interval is at slight future and tprev is not at slight future in zero_func

Yes that's the main issue, zero at the ends are handled poorly right now and its something that needs to be done. @tomaklutfu can you post the code which hits such peculiarities? Testing this float thing is the main roadblock for me right now as I don't have a single example right now which throws these errors. We may also add it to the tests.

**Comment by tomaklutfu** [comment]
Thanks for comments, but initial thought about counter intuitiveness of the comment remains. For a univariate f with first order aproximation around 0 is `f(θ) = f(0) + f'(0)*θ` so for `f'(0)>0` `f(0)` is up-crossing due to `f(θ)>0` regardless of order of the roots. I moved on with the code but I'll try to find a reproducer.

**Comment by kanav99** [comment]
Yes the comment is somewhat misleading. Lets get that updated. too.
I did understood your issue well and made an example and it does miss a callback - 
```julia
using OrdinaryDiffEq, Plots
function f(u,p,t)
  u
end

condition(u,t,integrator) = (t - 0.5)*(t - 0.6)
affect!(integrator) = println("ping")
cb = ContinuousCallback(condition,affect!)
u0 = 1.0
tspan = (0.0,1.0)
prob = ODEProblem(f,u0,tspan)
sol = solve(prob,Tsit5(),callback=cb,dt=0.1,adaptive=false)
```

**Comment by tomaklutfu** [comment]
@kanav99 @ChrisRackauckas have you tried the [gist](https://gist.github.com/tomaklutfu/f5b1a034014f3de06ec97acc8b88a950) I mentioned in the PR? This still errors. Reopen here maybe?

**Comment by ChrisRackauckas** [comment]
I didn't ever see the Gist.
