### ISSUE TITLE
Use CommonSolve.jl?

### ISSUE THREAD

**Issue by tkf** [SciML/DiffEqBase.jl#329]
Is there any plan to use CommonSolve.jl from DiffEqBase.jl?

**Comment by ChrisRackauckas** [comment]
Yes

**Comment by tkf** [comment]
Awesome!

**Comment by ChrisRackauckas** [comment]
Yeah I am planning to make DiffEqBase.init and DiffEqBase.solve actually just come from there, and open up a PR to JuMP so that way we no longer collide, and HomotopyContinuations.jl as well. Easy to do but takes a bit of time.

**Comment by tkf** [comment]
Sounds great. How about Optim and NLsolve?

**Comment by ChrisRackauckas** [comment]
I am going to make a problem type for nonlinear solving and optimization for other reasons, but in general those shouldn't use it for type piracy if they want to keep the same interface.

**Comment by tkf** [comment]
> a problem type for nonlinear solving and optimization

Sounds great :)

> if they want to keep the same interface

Right, my thought was more about having consistent "problem + algorithm -> solver (integrator) -> solution" pipelines everywhere.  But maybe they have good reasons to keep their current interface.  Also, if you are going to create problem types to wrap NLsolver/Optim that will effectively grant my wish anyway.

**Comment by ChrisRackauckas** [comment]
Done.
