### ISSUE TITLE
Continuous callbacks with DDEs broken since 6.25.1

### ISSUE THREAD

**Issue by devmotion** [SciML/DiffEqBase.jl#471]
I assume https://github.com/SciML/DiffEqBase.jl/pull/456 broke continuous callbacks with DDEs, e.g., compare https://travis-ci.org/github/SciML/DelayDiffEq.jl/jobs/665237645?utm_medium=notification&utm_source=github_status (DiffEqBase 6.25.0) with https://travis-ci.org/github/SciML/DelayDiffEq.jl/jobs/668097419?utm_medium=notification&utm_source=github_status (DiffEqBase 6.25.1).

I might have time to check what could have caused these regressions in the next days.

**Comment by ChrisRackauckas** [comment]
Thanks. @kanav99 should be noted too. We should make sure to add DelayDiffEq downstream tests to DiffEqBase to catch this in the future.

**Comment by kanav99** [comment]
This one is strange, I can have a loot at it today, this shouldn't have happened.

**Comment by kanav99** [comment]
@devmotion the problem is that now in callback solving, we stop at `prevfloat` (more generally on the opposite of tdir) of original root of callback. So `==` would not work now, we would need to make tests such that they work on approximates now.
