### ISSUE TITLE
default seed of zero incompatible with some rngs

### ISSUE THREAD

**Issue by isaacsas** [SciML/DiffEqBase.jl#522]
Throughout DiffEqBase default seeds are set to `Uint64(0)`. This is incompatible though with default generators we use in some SciML pacakges, for example the `Xoroshiro128star` generator in DiffEqJump. Could the default seed be changed? Perhaps it should be a more "random" number but saved in some variable, i.e. `DiffEqBase.DEFAULT_RNG_SEED`?

**Comment by ChrisRackauckas** [comment]
The zero is used as a sentinel: https://github.com/SciML/StochasticDiffEq.jl/blob/master/src/solve.jl#L66-L74

**Comment by isaacsas** [comment]
Hmm, for mixed constant jump/SDE systems it seems that zero is hanging around as the seed.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/StochasticDiffEq.jl/blob/master/src/solve.jl#L78-L80 probably need to be _seed.

**Comment by isaacsas** [comment]
I'll check out StochasticDiffEq master and see if that fixes the DiffEqJump tests.

**Comment by isaacsas** [comment]
Should be fixed by https://github.com/SciML/StochasticDiffEq.jl/pull/322
