### ISSUE TITLE
Too many includes in DiffEqBase.jl

### ISSUE THREAD

**Issue by Eggiverse** [SciML/DiffEqBase.jl#562]
I am wondering if it is better to move the `include`s into different files instead of putting everything in `DiffEqBase.jl`.

For example, make a new file `src/operators/operators.jl` and write
```julia
include("basic_operators.jl")
include("common_defaults.jl")
include("diffeq_operator.jl")
```
Then, we only need to `include("operators/operators.jl")` in `src/DiffEqBase.jl`.

Here, `operators.jl` works like `__init__.py` in python.

Furthermore, most codes are directly in module `DiffEqBase`. It seems to me putting them in some submodules would make it easier to maintain although `DiffEqBase` already works as a submodule in other packages of SciML.

**Comment by ChrisRackauckas** [comment]
I think that would be bad style and make it generally harder to maintain? I like having the top level module declare the features of the package, since otherwise there's no global view of what's going on.

**Comment by kanav99** [comment]
This would have made more sense if we had just one big package instead of many small ones.

**Comment by ChrisRackauckas** [comment]
Yes I think the split into subpackage effectively is that kind of submodule splitting.
