### ISSUE TITLE
No dimensionality checks on differential_vars --> solver passed uninitialized memory

### ISSUE THREAD

**Issue by dangirsh** [SciML/DiffEqBase.jl#581]
I've been testing a problem that has 3 variables, each spatially discretized into (let's say) Nₓ=10 elements. My`DAEProblem` looks like this:

```julia
du₀ = ComponentVector(c=zeros(Nₓ), Φᵉ=zeros(Nₓ), j=zeros(Nₓ))
differential_vars = [fill(true, Nₓ); fill(false, Nₓ); fill(false, Nₓ)]
dae_prob = DAEProblem(dae_func, du₀, u₀, tspan; differential_vars=differential_vars)
```

which seems to work. 

However, I had previously mistakenly had `differential_vars = [true, false, false]`, which seemed to be accepted by the solver. Glancing at the code, it looks like some uninitialized / zeroed memory was being silently passed through to Sundials in this case, leading to a very misleading bounds error on the solution.

My proposal is to add size checks to any input with this uninitialized memory hazard. Additionally / alternatively, we might add checks to the `DAEProblem` constructor as well. I'm not familiar with all the solver-specific uses for `differential_vars` to be sure, but it seems like a reasonable constraint based on [the docs](https://diffeq.sciml.ai/stable/types/dae_types/#Fields).

**Comment by dangirsh** [comment]
The PR should address this particular instance. There are likely several related issues I'm not yet aware of, since it doesn't looks like other problem constructors have this check. I'm happy to fix any that I'm pointed to. 

Are there any interfaces to non-memory-safe languages besides Sundials.jl?

**Comment by ChrisRackauckas** [comment]
A few. DASKR.jl is the only other one that would be effected by this, since the other DAE solvers are DASSL.jl and OrdinaryDiffEq.jl which are in Julia.
