### ISSUE TITLE
Investigating convergence issues with IterativeSolvers

### ISSUE THREAD

**Issue by rveltz** [SciML/DiffEqBase.jl#589]
Hi,

I am looking at matrix-free solver in the context of DE. I consider the [Brusselator 2d](https://diffeq.sciml.ai/stable/tutorials/advanced_ode_example/#Declaring-a-Jacobian-Free-Newton-Krylov-Implementation) which I collect for completeness.

I found something puzzling about the linear solve residuals which could boost the performances of DE. Additionally, I dont understand how to monitor the linear solves. Hopefully, this can be addressed easily.

```julia
using DifferentialEquations, Plots

const N = 32
const xyd_brusselator = range(0,stop=1,length=N)
brusselator_f(x, y, t) = (((x-0.3)^2 + (y-0.6)^2) <= 0.1^2) * (t >= 1.1) * 5.
limit(a, N) = a == N+1 ? 1 : a == 0 ? N : a

function brusselator_2d_loop(du, u, p, t)
  A, B, alpha, dx = p
  alpha = alpha/dx^2
  @inbounds for I in CartesianIndices((N, N))
    i, j = Tuple(I)
    x, y = xyd_brusselator[I[1]], xyd_brusselator[I[2]]
    ip1, im1, jp1, jm1 = limit(i+1, N), limit(i-1, N), limit(j+1, N), limit(j-1, N)
    du[i,j,1] = alpha*(u[im1,j,1] + u[ip1,j,1] + u[i,jp1,1] + u[i,jm1,1] - 4u[i,j,1]) +
                B + u[i,j,1]^2*u[i,j,2] - (A + 1)*u[i,j,1] + brusselator_f(x, y, t)
    du[i,j,2] = alpha*(u[im1,j,2] + u[ip1,j,2] + u[i,jp1,2] + u[i,jm1,2] - 4u[i,j,2]) +
                A*u[i,j,1] - u[i,j,1]^2*u[i,j,2]
    end
end
p = (3.4, 1., 10., step(xyd_brusselator))

using SparsityDetection, SparseArrays
input = rand(32,32,2)
output = similar(input)
sparsity_pattern = jacobian_sparsity(brusselator_2d_loop,output,input,p,0.0)
jac_sparsity = Float64.(sparse(sparsity_pattern))

f = ODEFunction(brusselator_2d_loop;jac_prototype=jac_sparsity)

function init_brusselator_2d(xyd)
  N = length(xyd)
  u = zeros(N, N, 2)
  for I in CartesianIndices((N, N))
    x = xyd[I[1]]
    y = xyd[I[2]]
    u[I,1] = 22*(y*(1-y))^(3/2)
    u[I,2] = 27*(x*(1-x))^(3/2)
  end
  u
end
u0 = init_brusselator_2d(xyd_brusselator)
prob_ode_brusselator_2d = ODEProblem(brusselator_2d_loop,
                                     u0,(0.,11.5),p)

using DiffEqOperators
Jv = JacVecOperator(brusselator_2d_loop,u0,p,0.0)
f2 = ODEFunction(brusselator_2d_loop;jac_prototype=Jv);
prob_ode_brusselator_2d_jacfree = ODEProblem(f2,u0,(0.,11.5),p);

using AlgebraicMultigrid
pc = aspreconditioner(ruge_stuben(jac_sparsity));
sol = @time DifferentialEquations.solve(prob_ode_brusselator_2d_jacfree,TRBDF2(linsolve=LinSolveGMRES( Pl=pc )),save_everystep=false) # 5.247 s (233048 allocations: 139.27 MiB)

heatmap(sol[end][:,:,1])
```

# Small Issue 1
If you look at the plot, you see that 
```julia
julia> maximum(sol[end][:,:,1])
1.8803021267519243e7
```

You dont see this blow up using `CVODE` which may be the reason for the slow down of DE.

## Fix
If you remove the preconditioner,
```julia
sol = @time DifferentialEquations.solve(prob_ode_brusselator_2d_jacfree,TRBDF2(linsolve=LinSolveGMRES()),save_everystep=false)
```
 it behaves like CVODE, ie gives the same solution. 

# Issue 2

Now, if you look at the convergence of the linear solves, but adding `@show IterativeSolvers.converged(iter)` just after this [line](https://github.com/SciML/DiffEqBase.jl/blob/master/src/linear_nonlinear.jl#L170), it always returns `false` and the residual seems large.

I thought about using the `verbose` keyword so that we can monitor the residuals by doing

```julia
sol = @time DifferentialEquations.solve(prob_ode_brusselator_2d_jacfree,TRBDF2(linsolve=LinSolveGMRES( kwargs = (verbose = true, log=true,) )),save_everystep=false)
```
but this returns an error.

## Improvement

I suggest to insert a warning for the user

```
IterativeSolvers.converged(iter) && @warn "Linear solve did not converged."
```
at this [line](https://github.com/SciML/DiffEqBase.jl/blob/master/src/linear_nonlinear.jl#L170).

**Comment by ChrisRackauckas** [comment]
>You dont see this blow up using CVODE which may be the reason for the slow down of DE.

CVODE uses the same preconditioner internally... so it's worth checking if we got it right.

>IterativeSolvers.converged(iter) && @warn "Linear solve did not converged."

We should throw all warnings back to DiffEq and treat them in a bigger system. This should actually cause a step rejection.

@YingboMa could you take a look at this.

**Comment by rveltz** [comment]
Additionally, it would be helpful to make this work `LinSolveGMRES( kwargs = (verbose = true, log=true,) )` if I am using the right command.

**Comment by ChrisRackauckas** [comment]
The new and improved tutorial https://diffeq.sciml.ai/stable/tutorials/advanced_ode_example/ showcases how to do the big models and preconditioning with all of the new LinearSolve.jl interfaces and surpasses CVODE's performance without preconditioning. CVODE GMRES with preconditioning is still slightly ahead of the chosen algorithm there, but those are just small performance tweaks left so I'll close this.
