### ISSUE TITLE
Bugs with ODE_DEFAULT_NORM

### ISSUE THREAD

**Issue by Gregstrq** [SciML/DiffEqBase.jl#619]
I detected several problems in the implementation of `ODE_DEFAULT_NORM` function. I listed them all together in one issue, because I believe they can be solved simultaneously.

- First of all, I noticed that `Vector` of arbitrary arrays inside an `ArrayPartition` breaks the function `ODE_DEFAULT_NORM` (see the file https://github.com/SciML/DiffEqBase.jl/blob/master/src/common_defaults.jl):
```
using RecursiveArrayTools, DiffEqBase

u = ArrayPartition((zeros(2), [zeros(2) for i = 1:2]))
DiffEqBase.ODE_DEFAULT_NORM(u, 0.0)
```
The last line leads to an error:
>ERROR: MethodError: no method matching abs2(::Array{Float64,1})
Closest candidates are:
  abs2(::Missing) at missing.jl:100
  abs2(::Bool) at bool.jl:84
  abs2(::ForwardDiff.Dual{T,V,N} where N where V) where T at ~/.julia/packages/ForwardDiff/qTmqf/src/dual.jl:201
>
 > ...
Stacktrace:
 [1] UNITLESS_ABS2 at ~/.julia/packages/DiffEqBase/CzrsV/src/common_defaults.jl:1 [inlined]
 ...
 [21] ODE_DEFAULT_NORM(::ArrayPartition{Float64,Tuple{Array{Float64,1},Array{Array{Float64,1},1}}}, ::Float64) at ~/.julia/packages/DiffEqBase/CzrsV/src/common_defaults.jl:9

- Secondly, there seems to be a bug in https://github.com/SciML/DiffEqBase.jl/blob/e3c4b11b2b1e677bf93b52abdb4d80a8819d058a/src/common_defaults.jl#L10
As far as I understand, the intention here is to sum over norms for each of the elements of `u`. However, it actually takes into account only the first component of `u`. The problem here is that `zip` function keeps iterating until one of the subiterators is exhausted. Since `t` is scalar, `zip` stops after the first iteration.
```
iter = zip([1,2,3,4], 0)
for elt in iter
    print(elt,"\n")
end
```
produces only
>(1, 0)

- Finally, the way it is organized right now, subarrays of different length acquire the same weight. Consider the following exaggerated example:
```
u = [[1.0], 2*ones(100)];
DiffEqBase.ODE_DEFAULT_NORM(u, 0.0)
```
Actually, due to the bug I described before, the output here is
>0.7071067811865476

But the intended outcome of the function is (if I understand the intention correctly)
```
sqrt(0.5*(DiffEqBase.ODE_DEFAULT_NORM(u[1], 0.0) + DiffEqBase.ODE_DEFAULT_NORM(u[2], 0.0))
```
which gives you
>1.224744871391589

Although the norm should be dominated by 100 elements with value 2, it is closer to 1.
**So, may be, as a default, one should treat all the elements of nested arrays on equal footing?**

**Comment by Gregstrq** [comment]
It seems that all three problems can be solved if we redefine `ODE_DEFAULT_NORM` as

```
@inline UNITLESS_ABS2(x::AbstractNumber) = real(abs2(x))
@inline UNITLESS_ABS2(x::AbstractArray) = sum(UNITLESS_ABS2, x)
@inline recursive_length(u::AbstractArray{<:AbstractNumber}) = length(u)
@inline recursive_length(u::AbstractArray{<:AbstractArray}) = sum(recursive_length, u)
@inline recursive_length(u::ArrayPartition) = sum(recursive_length, u.x)

@inline ODE_DEFAULT_NORM(u::AbstractArray, t) = sqrt(UNITLESS_ABS2(u)/recursive_length(u))
```
We can also leave the special dispatch for `typeof(u) <: Number`, `StaticArray`, `VectorOfArrays` for speed.

If it is important to keep the normalization of SubArrays as it is, than the first problem (Vector of Arrays inside ArrayPartition) is solved by the first two lines of code here, and one also needs to do something with zip function.

**Comment by ChrisRackauckas** [comment]
That's a good fix. Solving differential equations on arrays of arrays will still likely fail though because broadcast doesn't recurse? But this might make VectorOfArray work.

**Comment by Gregstrq** [comment]
Are you ok with changing the normalization of nested arrays?

**Comment by ChrisRackauckas** [comment]
Yes, it should be the total length. I think on ArrayPartition it should already be doing that?

**Comment by Gregstrq** [comment]
It is, but it handles only one level of nestedness: if you put a `Vector` of `StaticArray`s inside an `ArrayPartition`, it will just calculate the number of `StaticArray`s.

**Comment by Gregstrq** [comment]
By the way, why is there `real` all over the place? It seems that `abs2` returns a real number by default even on complex arguments.

**Comment by Gregstrq** [comment]
I have a question about `recursive_length`. It seems that this kind of function fits better inside RecursiveArrayTools.
What do you think about it?
