### ISSUE TITLE
Doc improvement to remove Warning caused by DataFrames change

### ISSUE THREAD

**Issue by ptoche** [SciML/DiffEqBase.jl#654]
From the first few paragraphs of [https://diffeq.sciml.ai/stable/features/io/](https://diffeq.sciml.ai/stable/features/io/)

    df = DataFrame(sol1)

throws the following Warning: 

    Warning: `DataFrame(columns::AbstractMatrix)` is deprecated, use `DataFrame(columns, :auto)` instead.
    │   caller = ip:0x0
    └ @ Core :-1

The correct syntax is now, if I understand correctly,

    df = DataFrame(sol1, :auto)

Reference: [https://discourse.julialang.org/t/what-does-dataframe-columns-abstractmatrix-is-deprecated-use-dataframe-columns-auto-mean/55997/2](https://discourse.julialang.org/t/what-does-dataframe-columns-abstractmatrix-is-deprecated-use-dataframe-columns-auto-mean/55997/2)

**Comment by ChrisRackauckas** [comment]
This should be handled by the tables integration though? @quinnj maybe knows what's up here.

**Comment by quinnj** [comment]
In Tables.jl, `AbstractMatrix` are not automatically treated as tables because they don't have column names. Tables.jl itself does provide two utility functions, however, in `Tables.table(mt)` to convert any `AbstractMatrix` into a valid "table", and `Tables.matrix(tbl)` to convert any valid "table" into a Matrix.

**Comment by ChrisRackauckas** [comment]
But the DESolution is already a table through its Tables.jl integration, so I don't get why that couldn't directly build a `DataFrame`?

**Comment by devmotion** [comment]
Because it just dispatches on `AbstractMatrix` but does not check if it implements the Tables.jl interface it seems: https://github.com/JuliaData/DataFrames.jl/blob/5579978e0bd3262125d2ddd1b8c2a0ad8540cac4/src/dataframe/dataframe.jl#L351

**Comment by devmotion** [comment]
Because it just dispatches on `AbstractMatrix` but does not check if it implements the Tables.jl interface it seems: https://github.com/JuliaData/DataFrames.jl/blob/8ce6f5f2be74bbd03a703e66b4da686a0748ab89/src/deprecated.jl#L126

**Comment by ChrisRackauckas** [comment]
Hmm, seems like a DataFrames.jl issue then? @bkamins

**Comment by ptoche** [comment]
This warning is going to show up everywhere, because many people (rightly or wrongly) do things like

    df = DataFrame(rand(6,100))

    ┌ Warning: `DataFrame(columns::AbstractMatrix)` is deprecated, use `DataFrame(columns, :auto)` instead.
     │   caller = ip:0x0
    └ @ Core :-1

**Comment by ChrisRackauckas** [comment]
Well I think the real issue is that if the traits are applied it shouldn't throw the warning, so this seems like a DataFrames.jl issue.

**Comment by ChrisRackauckas** [comment]
We can use `@requires` to add a dispatch for now to make it do the right thing though, but I presume this will be fixed by itself when the deprecation warning is removed?

**Comment by quinnj** [comment]
Yes, that seems correct to me. You could checkout DataFrames#main right now and test it out since it has been removed in preparation for the imminent 1.0 release.

**Comment by bkamins** [comment]
This is a deprecation because the standard policy is to have one round of releases in which we do not throw an error, but show deprecation. In 1.0 (and also currently in `main`) you will get:
```
julia> DataFrame([1 2; 3 4])
ERROR: ArgumentError: `DataFrame` constructor from a `Matrix` requires passing :auto as a second argument to automatically generate column names: `DataFrame(matrix, :auto)`
```
For `AbstractMatrix` that implements Tables.jl interface all should work. 1.0 will be released in ~2 weeks from now so double checking this would be welcome. Thank you!

**Comment by ChrisRackauckas** [comment]
I see. So

```julia
using OrdinaryDiffEq, DataFrames
f_2dlinear = (du,u,p,t) -> du.=1.01u;
prob = ODEProblem(f_2dlinear,rand(2,2),(0.0,1.0));
sol1 =solve(prob,Euler();dt=1//2^(4));
df = DataFrame(sol1)



17×5 DataFrame
 Row │ timestamp  value1    value2    value3    value4
     │ Float64    Float64   Float64   Float64   Float64
─────┼───────────────────────────────────────────────────
   1 │    0.0     0.131804  0.648837  0.120245  0.74758
   2 │    0.0625  0.140124  0.689794  0.127836  0.794772
   3 │    0.125   0.14897   0.733338  0.135906  0.844941
   4 │    0.1875  0.158373  0.77963   0.144485  0.898278
   5 │    0.25    0.168371  0.828844  0.153605  0.954982
   6 │    0.3125  0.178999  0.881164  0.163301  1.01527
   7 │    0.375   0.190298  0.936788  0.17361   1.07935
   8 │    0.4375  0.202311  0.995923  0.184569  1.14749
   9 │    0.5     0.215082  1.05879   0.19622   1.21992
  10 │    0.5625  0.228659  1.12563   0.208606  1.29693
  11 │    0.625   0.243093  1.19668   0.221775  1.3788
  12 │    0.6875  0.258438  1.27222   0.235774  1.46584
  13 │    0.75    0.274752  1.35253   0.250657  1.55837
  14 │    0.8125  0.292096  1.43791   0.26648   1.65674
  15 │    0.875   0.310534  …
```

works fine on master, so I'll close this given that it will be what's out in ~2 weeks.

**Comment by ptoche** [comment]
Please do close the issue, and thanks!
