### ISSUE TITLE
DEDataVector is not exported

### ISSUE THREAD

**Issue by ronisbr** [SciML/DiffEqBase.jl#700]
Hi!

I saw that `DEDataArrays` was marked as deprecated. We have now the package `DEDataArrays` that is used by this one. However, the `DEDataVector` is not exported, which broke a lot of things here. Hence, I have two questions:

1) Can we export `DEDataVector`?
2) If `DEDataArrays` is marked as deprecated, what is the substitute? I have a very specific problem related with control systems with a discrete part (as explained here https://ronanarraes.com/tutorials/julia/extending-ode-solutions-custom-data-arrays/). Notice that most of the part I want to save the discrete variables so that I can check the discrete part of the simulation (the embedded computer). Without `DEDataArray` how can I create this kind of workspace?

**Comment by ChrisRackauckas** [comment]
We can export it. I think we should tell people to start `using DEDataArrays` though.

**Comment by ronisbr** [comment]
I will submit a PR then!
