### ISSUE TITLE
bisection tests are broken

### ISSUE THREAD

**Issue by samuela** [SciML/DiffEqBase.jl#708]
```
julia> include("test/bisection_tests.jl")
ERROR: LoadError: MethodError: no method matching bisection(::typeof(sin), ::Tuple{Float64, Float64}, ::Float64)
Closest candidates are:
  bisection(::Any, ::Any, ::Bool, ::DiffEqBase.RootfindOpt, ::Any, ::Any; maxiters) at /home/skainswo/dev/DiffEqBase.jl/src/callbacks.jl:636
Stacktrace:
 [1] top-level scope
   @ ~/dev/DiffEqBase.jl/test/bisection_tests.jl:8
 [2] include(fname::String)
   @ Base.MainInclude ./client.jl:444
 [3] top-level scope
   @ REPL[2]:1
in expression starting at /home/skainswo/dev/DiffEqBase.jl/test/bisection_tests.jl:8
```
Curiously, `bisection_tests.jl` is absent from the test entrypoint `runtests.jl`: https://github.com/SciML/DiffEqBase.jl/blob/master/test/runtests.jl.

To reproduce:
* Clone DiffEqBase at 69e562b8dbb8a0b4dc19ae8efa1e1f1f32cbf395 (current master)
* `julia --project test/bisection_tests.jl`

**Comment by samuela** [comment]
More generally, are there any good example usages of `DiffEqBase.bisection` I could take a look at?

**Comment by ChrisRackauckas** [comment]
These days, the DiffEqBase.bisection is just a call to NonlinearSolve.jl's bisection, so the test here could be deleted.

**Comment by ChrisRackauckas** [comment]
Done.
