### ISSUE TITLE
Move  DiffEqBase.DAEInitializationAlgorithm to SciMLBase 

### ISSUE THREAD

**Issue by jd-lara** [SciML/DiffEqBase.jl#737]
Would be possible to move ` DiffEqBase.DAEInitializationAlgorithm` to SciML to be able to implement custom initialization methods without requiring the whole scope of DiffEqBase?

**Comment by ChrisRackauckas** [comment]
Yes, just copy it over, release, set a minimum version and delete. Should be a quick change.

**Comment by jd-lara** [comment]
DiffEqBase.DAEInitializationAlgorithm is already in SciML. The challenge remains on the definition of the function to initialize the dae
