### ISSUE TITLE
InternalFalsi (callback rootfinder) fails to solve ill-conditioned problem

### ISSUE THREAD

**Issue by DaniGlez** [SciML/DiffEqBase.jl#916]
This is a contrived example coming from https://github.com/SciML/OrdinaryDiffEq.jl/issues/1986 , but I'm having similar issues in saner cases as well. 

```julia

using SciMLBase, DiffEqBase
inp = IntervalNonlinearProblem((t, p) -> min(-1.0 + 0.001427344607477125 * t, 1e-9), (699.0079267259368, 700.6176418816023))
solve(inp, DiffEqBase.InternalFalsi()) # correct solution = 700.6016590257979 +/- one epsilon
# return u: 699.0079267259368 instead
```

**Comment by DaniGlez** [comment]
From my investigations, it seems that the issue is that the regula falsi solver [here](https://github.com/SciML/DiffEqBase.jl/blob/5fcbdeffd7f5f3f6bf07927e7519c2a0be17706c/src/internal_falsi.jl#L24) exhausts all the iterations while making insignificant progress (because it's close to the worst case scenario to regula Falsi, where the root is much closer to the side that is much farther from zero). Then, the backup bisection loop (with far better contraction rate) fails to execute as there are no iterations left. 

There are two easy solutions:
a) Leave enough iterations to the bisection solver. maxiters is 1000, with 500 the bisection can solve an interval of something like 1e133 in double precision if my math is sound
b) Interleave the Falsi iteration and the bisection. This seems much sounder to me: it degrades performance in the best case for regula falsi by a factor of <2 but it handles the ill-conditioned ones in more robust fashion.

I can make a PR for b), does that make sense?

**Comment by oscardssmith** [comment]
What about using an ITP method? That generally gives the best of both worlds.

**Comment by ChrisRackauckas** [comment]
> would the tests in test/downstream/community_callback_tests.jl be a good basis for comparison?

Yes that's probably the best we have.

**Comment by DaniGlez** [comment]
Crossposting the benchmarks: https://github.com/SciML/DiffEqBase.jl/pull/917#issuecomment-1641851819
