### ISSUE TITLE
Dispatch for `solve_up` for ReverseDiff is ambiguous

### ISSUE THREAD

**Issue by ThummeTo** [SciML/DiffEqBase.jl#946]
Hi @ChrisRackauckas,

there is a ambiguous dispatch for `solve_up`, if `u0::AbstractArray{<:ReverseDiff.TrackedReal}` and `p::TrackedArray`. This happens for example if one calls `solve` on an `ODEProblem` without the solver argument (to use the internal solver heuristic to determine one) - but I did not check why this happens in _exactly_ that case.

For example, [this MWE in SciMLSensitivity](https://github.com/SciML/SciMLSensitivity.jl/issues/863) can be used (it doesn't specify a solver) and it currently fails with the error message at the very bottom.

I wanted to provide a fix, but I was not sure why the initial state `u0` is converted from `AbstractArray{<:TrackedReal}` to `TrackedArray` in the [corresponding file](https://github.com/SciML/DiffEqBase.jl/blob/fb8028c6e1943ce78b77110101ab92551e15369e/ext/DiffEqBaseReverseDiffExt.jl#L111C15-L111C15) using `reduce(vcat, u0)`. This step prevents from using an in-place ODE, because mutating `TrackedArrays` is not allowed, however we could mutate `AbstractArray{<:TrackedReal}`. For my intuition, `p` should be converted to `TrackedArrays` (because immutable) but `u0` should stay a `AbstractArray{<:TrackedReal}` to allow for in-place modification? If this could be clarified, I can open a PR to fix this issue.

Best regards,
ThummeTo

----------

Error message
```
MethodError: kwcall(::NamedTuple{(:default_set, :saveat, :callback), Tuple{Bool, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, CallbackSet{Tuple{VectorContinuousCallback{typeof(condition), typeof(affect!), typeof(affect!), typeof(SciMLBase.INITIALIZE_DEFAULT), typeof(SciMLBase.FINALIZE_DEFAULT), Float64, Int64, Rational{Int64}, Nothing, Int64}}, Tuple{}}}}, ::typeof(solve_up), ::ODEProblem{Vector{ReverseDiff.TrackedReal{Float32, Float32, TrackedArray{Float32, Float32, 1, Vector{Float32}, Vector{Float32}}}}, Tuple{ReverseDiff.TrackedReal{Float32, Float32, TrackedArray{Float32, Float32, 1, Vector{Float32}, Vector{Float32}}}, ReverseDiff.TrackedReal{Float32, Float32, TrackedArray{Float32, Float32, 1, Vector{Float32}, Vector{Float32}}}}, true, TrackedArray{Float32, Float32, 1, Vector{Float32}, Vector{Float32}}, ODEFunction{true, SciMLBase.FullSpecialize, typeof(fx), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing}, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, SciMLBase.StandardODEProblem}, ::Nothing, ::TrackedArray{Float32, Float32, 1, Vector{Float32}, Vector{Float32}}, ::TrackedArray{Float32, Float32, 1, Vector{Float32}, Vector{Float32}}, ::CompositeAlgorithm{Tuple{Vern7{typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), Static.False}, Rodas5P{1, false, LinearSolve.DefaultLinearSolver, typeof(OrdinaryDiffEq.DEFAULT_PRECS), Val{:forward}, true, nothing}}, AutoSwitch{Vern7{typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), Static.False}, Rodas5P{0, false, Nothing, typeof(OrdinaryDiffEq.DEFAULT_PRECS), Val{:forward}, true, nothing}, Rational{Int64}, Int64}}) is ambiguous.
```

**Comment by ChrisRackauckas** [comment]
Try https://github.com/SciML/DiffEqBase.jl/pull/947

> I wanted to provide a fix, but I was not sure why the initial state u0 is converted from AbstractArray{<:TrackedReal} to TrackedArray in the [corresponding file](https://github.com/SciML/DiffEqBase.jl/blob/fb8028c6e1943ce78b77110101ab92551e15369e/ext/DiffEqBaseReverseDiffExt.jl#L111C15-L111C15) using reduce(vcat, u0).

That's to make the input into the adjoints uniform.

> This step prevents from using an in-place ODE, because mutating TrackedArrays is not allowed, however we could mutate AbstractArray{<:TrackedReal}.

No. If the analytical adjoint needs to use ReverseDiff for the vjp internally, then it can use TrackedArrays there. This is part of the capture mechanism though to say "okay you want to differentiate this ODE, so let's send it to an adjoint method because you did not choose to bypass the adjoint". And the adjoint method wants everything to start from TrackedArray form so that `ReverseDiff.track` works properly.
